branch-defaults:
  master:
    environment: EarlybirdBackend-env
environment-defaults:
  EarlybirdBackend-env:
    branch: null
    repository: null
global:
  application_name: earlybird-backend
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.4 running
    on 64bit Amazon Linux/3.0.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
