export const PING = 'EARLY_BIRD.PING'
export const GET_LATEST = 'EARLY_BIRD.GET_LATEST'
export const GET_UPGAPPERS = 'EARLY_BIRD.GET_UPGAPPERS'
export const GET_AFTER_HOURS = 'EARLY_BIRD.GET_AFTER_HOURS'