export const AUTH_SIGNUP = 'EARLY_BIRD.AUTH_SIGNUP'
export const AUTH_SIGNUP_FAIL = 'EARLY_BIRD.AUTH_SIGNUP_FAIL'
export const AUTH_SIGNUP_SUCCESS = 'EARLY_BIRD.AUTH_SIGNUP_SUCCESS'
export const AUTH_LOGOUT = 'EARLY_BIRD.AUTH_LOGOUT'
